import Head from 'next/head'
import { Button } from 'primereact/button';
import { Dialog } from 'primereact/dialog';


export default function Home() {
    return (
        <section>
            <Head>
                <title>CRUD Application</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="py-5">
                <h1 className="text-xl md:text-5xl text-center font-bold">Employee Management </h1>
            
                <div className="container mx-auto flex justify-between py-5 border-b">
                    <div className="left flex gap-3">
                        <Button icon="pi pi-user-plus" label="Add Employee" className="py-3" />
                    </div>
                </div>
            </div>
        </section>
    )
}
